# -*- coding: utf-8 -*-
"""ASSIGNMENT 4: Module 5: Files, Exceptions, and Errors in Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KcwD9h9ng9uaoWBSecosWkgubx6F8wM
"""

file = open("sample.txt", "w")
file.write("Line 1: This is a sample text file \n ")
file.write("Line 2:It Contents multiple lines \n")
file = open("sample.txt", "r")
file.close()

try:
    # Open the file
    file = open("sample.txt", "r")

    # Read and print each line
    for line in file:
        print(line.strip())

    # Close the file
    file.close()

except FileNotFoundError:
    # If file not found, print this message
    print("The file 'sample.txt' was not found.")

"""If File Not Found # Sample1.txt"""



try:
    # Open the file
    file = open("sample1.txt", "r")

    # Read and print each line
    for line in file:
        print(line.strip())

    # Close the file
    file.close()

except FileNotFoundError:
    # If file not found, print this message
    print("The file 'sample1.txt' was not found.")

#Task 2: Write and Append Data to a File

# Take user input and write to the file

text1 = input("Enter text to write to the file: ")
with open("output.txt", "w") as file:
    file.write(text1 + "\n")
print("Data Successfully written to ouotput.txt.")

# Append more text to the same file
text2 = input("Enter Additional text to append to the file: ")
with open("output.txt", "a") as file:
    file.write(text2 + "\n")
print("Data Successfully appended")

# Read and display the final content of the file
print("\nFinal content of output.txt:")
with open("output.txt", "r") as file:
    for line in file:
        print(line.strip())